http:
  port: "8081"
  
sfdc:
  username: "gauravchauhan@niit.com"
  password: "Gaurav@1122"
  token: "LfiXAmTI2mKfyPUE83uSJmdQN"

db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"