<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:eb="http://www.ebxml.org/namespaces/messageHeader" xmlns:or="http://services.sabre.com/res/or/v1_11" xmlns:ota="http://webservices.sabre.com/sabreXML/2003/07" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:stl1="http://webservices.sabre.com/pnrbuilder/v1_18" xmlns:stl2="http://services.sabre.com/STL/v01" xmlns:tns="http://webservices.sabre.com/pnrbuilder/getres" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="UpdateReservationWSDL" targetNamespace="http://webservices.sabre.com/pnrbuilder/getres">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="msg-header-2_0.xsd"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/ws/2002/12/secext" schemaLocation="wsse.xsd"/>

			<xsd:import namespace="http://webservices.sabre.com/pnrbuilder/v1_18" schemaLocation="PNRBuilderTypes_v1.18.0.xsd"/>
			<xsd:import namespace="http://webservices.sabre.com/pnrbuilder/v1_18" schemaLocation="UpdateReservationSTLRS_v1.18.0.xsd"/>
			<xsd:import namespace="http://webservices.sabre.com/pnrbuilder/v1_18" schemaLocation="UpdateReservationSTLRQ_v1.18.0.xsd"/>
			<xsd:import namespace="http://services.sabre.com/res/or/v1_12" schemaLocation="OpenReservation.1.12.0.xsd"/>
		</xsd:schema>
	</types>
	<message name="UpdateReservationInput">
		<part element="eb:MessageHeader" name="header"/>
		<part element="wsse:Security" name="header2"/>
		<part element="stl1:UpdateReservationRQ" name="body"/>
	</message>
	<message name="UpdateReservationOutput">
		<part element="eb:MessageHeader" name="header"/>
		<part element="wsse:Security" name="header2"/>
		<part element="stl1:UpdateReservationRS" name="body"/>
	</message>
	<portType name="UpdateReservationPortType">
		<operation name="UpdateReservationOperation">
			<input message="tns:UpdateReservationInput"/>
			<output message="tns:UpdateReservationOutput"/>
		</operation>
	</portType>
	<binding name="UpdateReservationSoapBinding" type="tns:UpdateReservationPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<operation name="UpdateReservationOperation">
            <soap:operation soapAction="UpdateReservationOperation"/>
			<input>
				<soap:header message="tns:UpdateReservationInput" part="header" use="literal"/>
				<soap:header message="tns:UpdateReservationInput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</input>
			<output>
				<soap:header message="tns:UpdateReservationOutput" part="header" use="literal"/>
				<soap:header message="tns:UpdateReservationOutput" part="header2" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="UpdateReservationService">
		<port binding="tns:UpdateReservationSoapBinding" name="UpdateReservationPortType">
			<soap:address location="http://localhost:8088/mockUpdateReservationSoapBinding"/>
		</port>
	</service>
</definitions>
