http:
  port: "8081"

american:
  host: "training4-american-api-{lastname}.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "0aad1e57e7054f16891d47850f20d270"
  client_secret: "292b459056Fe4fc99b58406466f2d580"